# wrangler.toml
[vars]
TELEGRAM_BOT_TOKEN = "123456789:ABCdefGHIjklMNOpqrsTUVwxyz"
TELEGRAM_CHANNEL_ID = "-1001234567890"
JWT_SECRET = "v9F3dR7xQpL8tNzC2mWbYkHjAeSsXfUv"

# !!! 重要：请将下面的 name 修改为一个全新的、从未使用过的名字 !!!
name = "online-cloud-cfwork" 
main = "src/index.js"
compatibility_date = "2024-03-20"

# 【Durable Object 绑定配置】
[[durable_objects.bindings]]
name = "USER_SPACE"
class_name = "UserSpace"

[[durable_objects.bindings]]
name = "STATS_AGGREGATOR"
class_name = "StatsAggregator"

# 【Durable Object 迁移配置】
[[migrations]]
tag = "v2"
new_sqlite_classes = ["UserSpace", "StatsAggregator"]




