# wrangler.toml

# !!! 重要：请将下面的 name 修改为一个全新的、从未使用过的名字 !!!
name = "my-cloud-drive-123" 
main = "src/index.js"
compatibility_date = "2024-03-20"

# 【Durable Object 绑定配置】
[[durable_objects.bindings]]
name = "USER_SPACE"
class_name = "UserSpace"

[[durable_objects.bindings]]
name = "STATS_AGGREGATOR"
class_name = "StatsAggregator"

# 【Durable Object 迁移配置】
[[migrations]]
tag = "v2"
new_sqlite_classes = ["UserSpace", "StatsAggregator"]
